artifact_uri: /mlflow_data/0/621e4e25133c41bc90e88639ae6bfee3/artifacts
end_time: 1740564676603
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 621e4e25133c41bc90e88639ae6bfee3
run_name: bustling-snake-901
run_uuid: 621e4e25133c41bc90e88639ae6bfee3
source_name: ''
source_type: 4
source_version: ''
start_time: 1740564673008
status: 3
tags: []
user_id: root
